#!/usr/bin/env python3
"""Build GitHub Pages content from Markdown.

Run ``python update.py`` after adding, editing, moving, or removing a file in
``markdowns/research/`` or ``markdowns/projects/``. The script regenerates the
browser content index, static route shells, sitemap, and cache version.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import shutil
import sys
from datetime import date
from pathlib import Path
from typing import Any
from xml.sax.saxutils import escape


ROOT = Path(__file__).resolve().parent
# (manifest key, editable Markdown source, public route collection)
CONTENT_SOURCES = (
    ("research", "markdowns/research", "blog"),
    ("projects", "markdowns/projects", "projects"),
)
FIXED_ROUTES = ("", "about", "services", "projects", "blog", "contact")
SLUG_RE = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
FRONT_MATTER_RE = re.compile(r"\A---\s*\n(.*?)\n---\s*(?:\n|\Z)", re.DOTALL)
SW_CACHE_RE = re.compile(r"const (CACHE|MD_CACHE) = 'bvec(?:-md)?-[^']+';")
ACRONYMS = {
    "api": "API", "appsec": "AppSec", "aws": "AWS", "c2": "C2",
    "gcp": "GCP", "git": "Git", "grpc": "gRPC", "iam": "IAM",
    "iot": "IoT", "osint": "OSINT", "oauth": "OAuth", "qemu": "QEMU",
    "saml": "SAML", "sql": "SQL", "sso": "SSO", "tls": "TLS",
}


class ContentError(ValueError):
    """Raised when a Markdown content file cannot be published safely."""


def parse_front_matter(path: Path) -> dict[str, str]:
    text = path.read_text(encoding="utf-8")
    match = FRONT_MATTER_RE.match(text)
    if not match:
        raise ContentError(f"{path.relative_to(ROOT)}: missing YAML front matter")

    metadata: dict[str, str] = {}
    for line_number, line in enumerate(match.group(1).splitlines(), start=2):
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        if ":" not in line:
            raise ContentError(f"{path.relative_to(ROOT)}:{line_number}: expected key: value")
        key, value = line.split(":", 1)
        key, value = key.strip(), value.strip()
        if not key or not value:
            raise ContentError(f"{path.relative_to(ROOT)}:{line_number}: empty front-matter key or value")
        if value[:1] in {"'", '"'} and value[-1:] == value[:1]:
            value = value[1:-1]
        metadata[key] = value
    return metadata


def display_tag(tag: str) -> str:
    words = []
    for word in tag.strip().replace("_", "-").split("-"):
        clean = word.lower()
        words.append(ACRONYMS.get(clean, word.capitalize()))
    return " ".join(words)


def content_item(path: Path, section: str) -> dict[str, Any]:
    slug = path.stem
    if not SLUG_RE.fullmatch(slug):
        raise ContentError(f"{path.relative_to(ROOT)}: filename must be a lowercase kebab-case slug")
    fm = parse_front_matter(path)
    required = ("title", "date", "excerpt")
    missing = [field for field in required if not fm.get(field)]
    if missing:
        raise ContentError(f"{path.relative_to(ROOT)}: missing required field(s): {', '.join(missing)}")
    try:
        date.fromisoformat(fm["date"])
    except ValueError as error:
        raise ContentError(f"{path.relative_to(ROOT)}: date must use YYYY-MM-DD") from error

    tags = [display_tag(tag) for tag in fm.get("tags", "").split(",") if tag.strip()]
    if section == "research" and not tags:
        raise ContentError(f"{path.relative_to(ROOT)}: research posts require at least one tag")

    item: dict[str, Any] = {
        "slug": slug,
        "title": fm["title"],
        "date": fm["date"],
        "tags": tags,
        "excerpt": fm["excerpt"],
    }
    for key in ("status", "stack", "link", "role", "author"):
        if fm.get(key):
            item[key] = fm[key]
    return item


def collect_content() -> dict[str, list[dict[str, Any]]]:
    content: dict[str, list[dict[str, Any]]] = {}
    for section, source_dir, _ in CONTENT_SOURCES:
        directory = ROOT / source_dir
        if not directory.is_dir():
            raise ContentError(f"Missing content directory: {source_dir}/")
        items = [content_item(path, section) for path in sorted(directory.glob("*.md"))]
        if len({item["slug"] for item in items}) != len(items):
            raise ContentError(f"Duplicate slugs found in {source_dir}/")
        content[section] = sorted(items, key=lambda item: item["date"], reverse=True)
    return content


def write_if_changed(path: Path, text: str, check: bool) -> bool:
    existing = path.read_text(encoding="utf-8") if path.exists() else None
    changed = existing != text
    if changed and not check:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
    return changed


def render_content_index(content: dict[str, list[dict[str, Any]]]) -> str:
    payload = {"research": content["research"], "projects": content["projects"]}
    return "/* Generated by update.py — do not edit manually. */\nwindow.BLACKVECTR_CONTENT_INDEX = " + json.dumps(payload, ensure_ascii=False, separators=(",", ":")) + ";\n"


def site_url() -> str:
    cname = ROOT / "CNAME"
    domain = cname.read_text(encoding="utf-8").strip() if cname.exists() else ""
    if not domain:
        raise ContentError("CNAME must contain the GitHub Pages domain used for sitemap URLs")
    return f"https://{domain.rstrip('/') }"


def render_sitemap(content: dict[str, list[dict[str, Any]]]) -> str:
    base = site_url()
    entries: list[tuple[str, str, str | None]] = [
        ("/", "1.0", None), ("/about", "0.8", None), ("/services", "0.9", None),
        ("/projects", "0.8", None), ("/blog", "0.7", None), ("/contact", "0.6", None),
    ]
    entries.extend((f"/blog/{item['slug']}", "0.6", item["date"]) for item in content["research"])
    entries.extend((f"/projects/{item['slug']}", "0.6", item["date"]) for item in content["projects"])
    lines = ['<?xml version="1.0" encoding="UTF-8"?>', '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">']
    for path, priority, lastmod in entries:
        row = f"  <url><loc>{escape(base + path)}</loc>"
        if lastmod:
            row += f"<lastmod>{lastmod}</lastmod>"
        lines.append(row + f"<priority>{priority}</priority></url>")
    lines.append("</urlset>")
    return "\n".join(lines) + "\n"


def generate_routes(content: dict[str, list[dict[str, Any]]], check: bool) -> bool:
    shell = (ROOT / "index.html").read_text(encoding="utf-8")
    routes = set(FIXED_ROUTES)
    for section, _, output_dir in CONTENT_SOURCES:
        routes.update(f"{output_dir}/{item['slug']}" for item in content[section])

    changed = False
    for route in sorted(routes):
        if not route:
            continue
        changed |= write_if_changed(ROOT / route / "index.html", shell, check)
    changed |= write_if_changed(ROOT / "404.html", shell, check)

    # A moved or deleted Markdown file must not leave an indexable stale route.
    for _, _, output_dir in CONTENT_SOURCES:
        current_slugs = {route.rsplit("/", 1)[-1] for route in routes if route.startswith(output_dir + "/")}
        for child in (ROOT / output_dir).iterdir():
            route_shell = child / "index.html"
            if not child.is_dir() or child.name in current_slugs or not route_shell.is_file():
                continue
            # Generated routes contain only the shared app shell. Preserve custom pages.
            if any(path.name != "index.html" for path in child.iterdir()):
                continue
            if "data-pages-base" not in route_shell.read_text(encoding="utf-8"):
                continue
            changed = True
            if not check:
                shutil.rmtree(child)
    return changed


def update_service_worker(content: dict[str, list[dict[str, Any]]], check: bool) -> bool:
    path = ROOT / "sw.js"
    source = path.read_text(encoding="utf-8")
    fingerprint_source = (ROOT / "index.html").read_bytes() + (ROOT / "assets/js/app.js").read_bytes() + json.dumps(content, sort_keys=True).encode()
    version = hashlib.sha256(fingerprint_source).hexdigest()[:12]
    replacements = {"CACHE": f"bvec-{version}", "MD_CACHE": f"bvec-md-{version}"}

    def replace(match: re.Match[str]) -> str:
        name = match.group(1)
        return f"const {name} = '{replacements[name]}';"

    updated, count = SW_CACHE_RE.subn(replace, source)
    if count != 2:
        raise ContentError("sw.js must define CACHE and MD_CACHE using bvec cache names")
    return write_if_changed(path, updated, check)


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate GitHub Pages content assets from Markdown.")
    parser.add_argument("--check", action="store_true", help="Report stale generated files without writing them.")
    args = parser.parse_args()
    try:
        content = collect_content()
        changes = {
            "assets/js/content-index.js": write_if_changed(ROOT / "assets/js/content-index.js", render_content_index(content), args.check),
            "sitemap.xml": write_if_changed(ROOT / "sitemap.xml", render_sitemap(content), args.check),
            "static routes": generate_routes(content, args.check),
            "sw.js": update_service_worker(content, args.check),
        }
    except ContentError as error:
        print(f"update.py: error: {error}", file=sys.stderr)
        return 1

    changed = [name for name, did_change in changes.items() if did_change]
    if args.check:
        if changed:
            print("Generated files are out of date: " + ", ".join(changed), file=sys.stderr)
            return 1
        print("Generated files are up to date.")
    else:
        print("Updated: " + (", ".join(changed) if changed else "nothing (already up to date)"))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
